### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mzch** [easyflow-live/easyflow#1]
I setup Firebase and easyflow, and `npm start` then tried to login, but easyflow showed a pop-up window shortly and closed immediately. Nothing else happened. easyflow.live behaves in a same action. How can I fix this?

**Comment by delete** [comment]
Did you add `localhost` and the `REACT_APP_AUTH_DOMAIN` domain as  **Authorized domains** in Firebase Authentication Providers?

**Comment by mzch** [comment]
Yes.

**Comment by mzch** [comment]
When set `kanbanie.com` to `REACT_APP_AUTH_DOMAIN`, 404 error on `https://kanbanie.com/__/auth/iframe?apiKey=xxxxx&appName=%5BDEFAULT%5D&v=5.11.0&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.ja.EuGEpihn8s0.O%2Fam%3DwQE%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCNCct2tNVstwAjYIcHk6Wqkev8abQ%2Fm%3D__features__`

<img width="553" alt="ScreenShot 2020-02-20 6 36 13" src="https://user-images.githubusercontent.com/621178/74879103-cd791900-53ab-11ea-821f-ee20082ece1a.png">

When set `xxx.firebaseapp.com` to `REACT_APP_AUTH_DOMAIN`, an error, `This browser is not supported or 3rd party cookies and data may be disabled.`

<img width="553" alt="ScreenShot 2020-02-20 6 48 18" src="https://user-images.githubusercontent.com/621178/74879854-60668300-53ad-11ea-9f71-57be2cb81127.png">

**Comment by mzch** [comment]
On Chrome, 80.0.3987.116, an above error occurred.
On Firefox, 72.0.2, and Safari, 13.05, can login but I couldn’t add boards because there is no button nor no link in the page. `Error: Missing or insufficient permissions. https://kanbanie.com/_next/static/chunks/484bcb1e.ad559ab8dcb5da48d174.js`

**Comment by mzch** [comment]
On Safari and Firefox, when switching `allow read, write if true`, `Add new board` button appears.
But on Chome, the issue hasn't  been fixed yet.

**Comment by delete** [comment]
Please, can you try to run local without your custom domain? Just using the Firebase default configs. 
I'm not sure what is happening, because I just forked it and created a new Firebase APP, and it's look good.

**Comment by mzch** [comment]
Yes, I did both custom domain and default domain. I create CNAME record in DNS pointed at `easy-flow-99554.firebaseapp.com`.
And on Chrome, the kind of error was changed to network error...Any idea?

<img width="553" alt="ScreenShot 2020-02-20 8 50 02" src="https://user-images.githubusercontent.com/621178/74887384-1cc84500-53be-11ea-912b-aefc72bc9f9d.png">

**Comment by delete** [comment]
Sorry, I really don't know. I don't think this is an easyflow problem.

Maybe CORS related? Do you use any adblock extension?

**Comment by mzch** [comment]
Oh, yes. I use Adblock Plus, but I added my domain and firebaseapp.com to whitelist.
And I uninstalled Adblock Plus, then tried but the same error.
Is this related with https://www.chromium.org/updates/same-site?

**Comment by mzch** [comment]
I tried Vivaldi, Brave Browser. They caused the same errors.
It seems to happen errors on Chromium base browsers.
Please try https://kanbanie.com

**Comment by mzch** [comment]
When accessing `https://easyflow.live`, the same error occurred.

<img width="553" alt="ScreenShot  2020-02-20 21 15 35" src="https://user-images.githubusercontent.com/621178/74932941-52a11400-5426-11ea-8f52-ff5ce1e94dda.png">

**Comment by delete** [comment]
I do have this problem when accessing `https://kanbanie.com`.

But with https://easyflow.live works fine (already logged in)

![Screen Shot 2020-02-20 at 11 55 29 AM](https://user-images.githubusercontent.com/434694/74946382-f31c1780-53d7-11ea-841f-e9d1b8c2166e.png)

Take a look at this https://github.com/firebase/firebase-js-sdk/issues/865

**Comment by mzch** [comment]
I have already read those articles.

I reset all histories and cookies of Chrome and other browsers, then I confirmed to be able to connect https://easyflow.live using Vivaldi. When disabling Shields on Brave Browser, it was able to connect https://easyflow.live correctly. (When enabling Shields, failed to connect because 3rd party cookie.) And  in case of Chrome 80, it reported. 'This browser is not supported or 3rd party cookies and data may be disabled'. So I disabled 3rd party cookie block. then Chrome works well on https://easyflow.live.

And when connecting https://kanbanie.com, an error occurred, 'Network error'... What am I doing wrong?

- I created .env as follows and ran `npm run build`
```
REACT_APP_API_KEY = xxx
REACT_APP_AUTH_DOMAIN = auth.kanbanie.com
REACT_APP_DATABASE_URL = https://my-app.firebaseio.com
REACT_APP_PROJECT_ID = my-app
REACT_APP_STORAGE_BUCKET = my-app.appspot.com
REACT_APP_MESSAGING_SENDER_ID = 999
REACT_APP_ID = 1:999:web:xxx
PORT = 3333
```

Of course. I added `auth.kanbanie.com` to authorized domain on Firebase console and DNS pointed to my-app.firebaseapp.com

**Comment by mzch** [comment]
Well, Once I changed `REACT_APP_AUTH_DOMAIN` to `my-app.firebaseapp.com`, Everything goes well.

**Comment by delete** [comment]
Something may be wrong with the DNS. I coun't change mine either,  I'm still using `*.firebase.com `as `REACT_APP_AUTH_DOMAIN`.

**Comment by mzch** [comment]
I'm also going to use `*.firebase.com`. Thanks for your time and effort! :)
